inherit_from:
- .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'spec/*'
    - 'app/helpers/application_helper.rb'
    - 'app/uploaders/image_uploader.rb'
# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false
